### ISSUE TITLE
 ModuleNotFoundError: No module named 'pip' when not using a venv

### ISSUE THREAD

**Issue by agirault** [karellen/wheel-axle-runtime#10] opened 2023-09-06 18:59 UTC
## Environment

Using pip3 on a Linux system (not venv) requires to install it with `sudo apt install python3-pip`, which puts it in `/usr/lib/python3/dist-packages`. It can also be installed system wide under `/usr/local/lib/python3.x/dist-packages` with `sudo`

Example on Ubuntu 22.04:
```
$ pip3 --version
pip 22.0.2 from /usr/lib/python3/dist-packages/pip (python 3.10)
```

## Error

With that installation (instead of `$HOME/.local/lib/python3.y/site-packages`), the following error will occur when running python3 from any `pth` file generated by `wheel-axle-runtime`:
```
Error processing line 5 of /home/nvidia/.local/lib/python3.10/site-packages/<mypackage>-<version>.pth:

  Traceback (most recent call last):
    File "/usr/lib/python3.10/site.py", line 192, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
    File "/home/nvidia/.local/lib/python3.10/site-packages/wheel_axle/runtime/__init__.py", line 52, in finalize
      from wheel_axle.runtime._symlinks import SymlinksInstaller
    File "/home/nvidia/.local/lib/python3.10/site-packages/wheel_axle/runtime/_symlinks.py", line 22, in <module>
      from pip._internal.models.scheme import SCHEME_KEYS
  ModuleNotFoundError: No module named 'pip
```

## Explanation

This is because the `pth` file has a limited `sys.path`, which can be confirmed with the following test file added to `$HOME/.local/lib/python3.10/site-packages/test_path.pth`:
```py
import sys; print(sys.path)
```
will return:
```
['/usr/lib/python310.zip', '/usr/lib/python3.10', '/usr/lib/python3.10/lib-dynload', '$HOME/.local/lib/python3.10/site-packages']
```
while calling the following:
```bash
python3 -c "import sys; print(sys.path)"
```
returns:
```
['$HOME/.local/lib/python3.10/site-packages', '/usr/lib/python310.zip', '/usr/lib/python3.10', '/usr/lib/python3.10/lib-dynload', '$HOME/.local/lib/python3.10/site-packages', '/usr/local/lib/python3.10/dist-packages', '/usr/lib/python3/dist-packages', '/usr/lib/python3.10/dist-packages']
```
Missing sites are:
- '/usr/local/lib/python3.10/dist-packages'
- '/usr/lib/python3/dist-packages'
- '/usr/lib/python3.10/dist-packages'

## Solutions

A mitigation is for the user to install pip manually in the user space.

A better solution would be to ensure the system dist-packages are considered in the `pth` file. This could be done in two ways:
1. Prepend this single line to the `pth` file. It uses the `exec` mode since it starts with `import`:
```py
import sys; pythonx = f'python{sys.version_info.major}'; pythonxy = f'pythonx.{sys.version_info.minor}'; sys.path.extend([f'/usr/local/lib/{pythonxy}/dist-packages', f'/usr/lib/{pythonx}/dist-packages', f'/usr/lib/{pythonxy}/dist-packages'])
```
2. Prepend these three lines to the `pth` file, where `<major>` and `<minor>` are dynamically set when writing that file, assuming it is known then?
```pth
/usr/local/lib/python<major>.<minor>/dist-packages
/usr/lib/python<major>/dist-packages
/usr/lib/python<major>.<minor>/dist-packages
```

**Comment by arcivanov** [comment] 2023-09-06 19:04
Ooof. This is installation/OS-specific. Let me check on Fedora, it might be different.

**Comment by arcivanov** [comment] 2023-09-06 19:09
Also, while not strictly prohibited, generally `wheel-axle` is **not** for system-wide installations. It should work with `$HOME/.local`.

Btw I'm not following this passage:

> Using pip3 on a Linux system (not venv) requires to install it with sudo apt install python3-pip, which puts it in /usr/lib/python3/dist-packages. It can also be installed system wide under /usr/local/lib/python3.x/dist-packages with sudo

`/usr/lib/python3/dist-packages` and `/usr/local/lib` are system-wide, no? Just one is system package the other one is user-installed optional. I'm not firm in my understanding of how Ubuntu does it. You can't install either without `sudo`.

**Comment by arcivanov** [comment] 2023-09-06 19:45
Well, the simplest solution then will be to make `wheel-axle-runtime` explicitly depend on `pip`, right?

**Comment by agirault** [comment] 2023-09-06 20:24
If `pip` is already installed on the system, adding a dependency to `pip` will be already resolved and it won't install it in `$HOME/.local`. The only way this would work was if the dependency was on a version of `pip` that is guaranteed to not be installed on the system already.

**Comment by arcivanov** [comment] 2023-09-07 03:42
Ugh... so this is what's going on:

https://github.com/python/cpython/blob/1ebe014d62a700514c7dce8fd0b4d6b6d7929835/Lib/site.py#L602-L603

This is a potentially a bug in Python `site.py` - while the order of sys.path is correct, the initialization order is not - the site packages should be initialized before user site packages.

I think I know how to create a workaround.

**Comment by agirault** [comment] 2023-09-07 14:41
Calling `addsitepackages` inside the pth file?

**Comment by arcivanov** [comment] 2023-09-07 18:36
@agirault the issue is the order in which they are called. While the paths are produced in the correct order the implied dependencies are not.  It's a subtle bug that's been around for I guess 20 years.

**Comment by arcivanov** [comment] 2023-09-07 18:38
I can work around it by doing stuff with `sys.path` manipulation in my code and doing `addsitepackages` with `try-finally` substituting `sys.path`.

**Comment by arcivanov** [comment] 2023-09-08 00:19
Just FYI, while I implemented the fix for the `import pip` issue, it's not the only thing that is required.

This current installation schema is in a "TODO" stage: https://github.com/karellen/wheel-axle-runtime/blob/74ee2eae2325418ea354730c8143a5b5dff3ae25/README.md?plain=1#L88

So resolving the purely the import issue results in the following:

```
$ python -c pass
Error processing line 1 of /home/arcivanov/.local/lib/python3.11/site-packages/karellen_llvm_core-16.0.6.pth:

  Traceback (most recent call last):
    File "<frozen site>", line 186, in addpackage
    File "<string>", line 1, in <module>
    File "/home/arcivanov/.local/lib/python3.11/site-packages/wheel_axle/runtime/__init__.py", line 86, in finalize
      _run_installers(dist_info_dir)
    File "/home/arcivanov/.local/lib/python3.11/site-packages/wheel_axle/runtime/__init__.py", line 40, in _run_installers
      installer(dist_info_dir).run()
    File "/home/arcivanov/.local/lib/python3.11/site-packages/wheel_axle/runtime/_common.py", line 53, in run
      self.scheme = get_current_scheme(dist_info_dir, self.dist_meta.project_name, self.wheel_meta)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/arcivanov/.local/lib/python3.11/site-packages/wheel_axle/runtime/_wheel.py", line 75, in get_current_scheme
      if check_correct_scheme(scheme, install_dir):
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/arcivanov/.local/lib/python3.11/site-packages/wheel_axle/runtime/_wheel.py", line 70, in check_correct_scheme
      if os.path.samefile(install_dir, scheme_dir):
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "<frozen genericpath>", line 101, in samefile
  FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib64/python3.11/site-packages'
```

**Closed** 2023-09-08 03:52 UTC

**Comment by arcivanov** [comment] 2023-09-08 04:05
@agirault It's done, please test your package by installing `pip install --pre wheel-axle-runtime`: https://pypi.org/project/wheel-axle-runtime/0.0.5.dev20230908035349/

Please let me know if the release is working for you and I'll bump the latest stable.

**Comment by arcivanov** [comment] 2023-09-08 12:22
@agirault please confirm when able so I can cut a release

**Comment by arcivanov** [comment] 2023-09-19 17:32
Thanks for letting me know. I think it's been fixed, at least I was able to reproduce the issue and it's not an issue anymore.
